# Generated by Django 6.0.5 on 2026-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('archived', 'Архив')], default='active', max_length=15, verbose_name='Статус'),
        ),
    ]
